# Generated by Django 3.2 on 2022-01-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bookstore', '0004_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
