# Generated by Django 3.2 on 2022-01-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bookstore', '0005_alter_author_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
